### ISSUE TITLE
[BUG]: Possible typo

### ISSUE THREAD

**Issue by denlove** [KislotaRU/CS-Learning#1]
### 1. Описание бага*
_Название файла_ и _класса_ выглядят подозрительно, будто с опечаткой. А именно, слово `CorrentTask`.

### 2. Какое поведение вызвало баг?*
После открытия файла.

### 3. Ожидаемое поведение*
Если автор имел в виду английское слово "_Current_" (текущий), то следует исправить название файла и класса на `CurrentTask`.

#

https://github.com/KislotaRU/CS-Learning/blob/dd103ff93ebb9cfa0a6e21996f1edf2ca4675984/CS%20JUNIOR/CorrentTask.cs#L13

**Comment by KislotaRU** [comment]
Спасибо, [@denlove](url), за нахождение опечатки.
**В работе.**
